// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCa0UmUsYNTnbcJBSRhkENOYjhgTHbYmQc',
    appId: '1:564726691203:web:6b6594956898d8f56332b6',
    messagingSenderId: '564726691203',
    projectId: 'student-hub-7c50c',
    authDomain: 'student-hub-7c50c.firebaseapp.com',
    storageBucket: 'student-hub-7c50c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB_B6Dzarl6O-91BlE2sghcZ6NFkpEH1aQ',
    appId: '1:564726691203:android:15aca23b7d8b691f6332b6',
    messagingSenderId: '564726691203',
    projectId: 'student-hub-7c50c',
    storageBucket: 'student-hub-7c50c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFdIRXvyJKBH6zM8nk0ikaOOtxsi6v3mM',
    appId: '1:564726691203:ios:1b130fac200ebb1b6332b6',
    messagingSenderId: '564726691203',
    projectId: 'student-hub-7c50c',
    storageBucket: 'student-hub-7c50c.firebasestorage.app',
    iosBundleId: 'com.example.linkedin',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFdIRXvyJKBH6zM8nk0ikaOOtxsi6v3mM',
    appId: '1:564726691203:ios:1b130fac200ebb1b6332b6',
    messagingSenderId: '564726691203',
    projectId: 'student-hub-7c50c',
    storageBucket: 'student-hub-7c50c.firebasestorage.app',
    iosBundleId: 'com.example.linkedin',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCa0UmUsYNTnbcJBSRhkENOYjhgTHbYmQc',
    appId: '1:564726691203:web:9af1a1ddc2c3e2876332b6',
    messagingSenderId: '564726691203',
    projectId: 'student-hub-7c50c',
    authDomain: 'student-hub-7c50c.firebaseapp.com',
    storageBucket: 'student-hub-7c50c.firebasestorage.app',
  );
}
